title: "Waves.Fi - DeFi Node"
tagline: "DeFi Enabled WAVES NODE"
description: " A Staking Yield Aggregator"
twitter_username: Waves_Finance
baseurl: "/"
url: "https://waves.fi"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - about.md
  - roadmap.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
